### ISSUE TITLE
Too many .version files in 1.0.3 download

### ISSUE THREAD

**Issue by HebaruSan** [linuxgurugamer/ZZZ-RadioTelescope#3]
Current release is failing validation in the CKAN bot:

Too many .version files located: GameData/MunSeeker/ZZZ_RadioTelescope/ZZZRadioTelescope.version, GameData/MunSeeker/ZZZRadioTelescope.version

Looks like both are wrong, since SpaceDock says this is for KSP 1.6.1, but the .version files say KSP 1.2.2 and 1.4.5.

**Comment by linuxgurugamer** [comment]
Fixed, new version  1.0.3.1 uploaded to both Spacedock and Github
